#### kidney dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv()

In [14]:
if "DoctorInCharge" in df.columns:
    df.drop(columns=["DoctorInCharge"], inplace=True)

In [15]:
save_path = r"C:\Users\Jashwanth\OneDrive\Documents\MEDPREDICT\Cleaned Datasets\cleaned_Chronic_Kidney_Disease_data.csv"

# Save the cleaned dataset
df.to_csv(save_path, index=False)

print(f"File saved successfully at: {save_path}")

File saved successfully at: C:\Users\Jashwanth\OneDrive\Documents\MEDPREDICT\Cleaned Datasets\cleaned_Chronic_Kidney_Disease_data.csv

#### fatty liver disease data

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv(r'C:\Users\Jashwanth\Downloads\transformed_nafld1.csv')
df.head()

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
0,3631,1,57,0,60.0,163.0,22.690939,10630.0,6261,0
1,8458,2,67,0,70.4,168.0,24.884028,14817.0,624,0
2,6298,3,53,1,105.8,186.0,30.453537,3.0,1783,0
3,15398,4,56,1,109.3,170.0,37.830100,6628.0,3143,0
4,13261,5,68,1,NaN,NaN,NaN,1871.0,1836,1

In [18]:
if "Unnamed: 0" in df.columns:
    df.drop(columns=["Unnamed: 0"], inplace=True)

In [19]:
save_path = r"C:\Users\Jashwanth\OneDrive\Documents\MEDPREDICT\Cleaned Datasets\cleaned_nafld1.csv"

# Save the cleaned dataset
df.to_csv(save_path, index=False)

print(f"File saved successfully at: {save_path}")

File saved successfully at: C:\Users\Jashwanth\OneDrive\Documents\MEDPREDICT\Cleaned Datasets\cleaned_nafld1.csv

#### obesity

In [22]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [23]:
df = pd.read_csv(r'C:\Users\Jashwanth\OneDrive\Documents\MEDPREDICT\Datasets/ObesityDataSet_raw_and_data_sinthetic.csv')  
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [24]:
categorical_cols = df.select_dtypes(include=["object"]).columns

label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

transformed_file_path = "C:/Users/Jashwanth/OneDrive/Documents/MEDPREDICT/Cleaned Datasets/transformed_ObesityDataSet.csv"  
df.to_csv(transformed_file_path, index=False)

print("Transformation complete. File saved at:", transformed_file_path)

Transformation complete. File saved at: C:/Users/Jashwanth/OneDrive/Documents/MEDPREDICT/Cleaned Datasets/transformed_ObesityDataSet.csv

### thyroid

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [27]:
df = pd.read_csv(r'C:/Users/Jashwanth/OneDrive/Documents/MEDPREDICT/Datasets/Thyroid_Diff.csv')
df.head()

,Age,Gender,Smoking,Hx Smoking,Hx Radiothreapy,Thyroid Function,Physical Examination,Adenopathy,Pathology,Focality,Risk,T,N,M,Stage,Response,Recurred
0,27,F,No,No,No,Euthyroid,Single nodular goiter-left,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Indeterminate,No
1,34,F,No,Yes,No,Euthyroid,Multinodular goiter,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
2,30,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
3,62,F,No,No,No,Euthyroid,Single nodular goiter-right,No,Micropapillary,Uni-Focal,Low,T1a,N0,M0,I,Excellent,No
4,62,F,No,No,No,Euthyroid,Multinodular goiter,No,Micropapillary,Multi-Focal,Low,T1a,N0,M0,I,Excellent,No

In [28]:
categorical_cols = df.select_dtypes(include=["object"]).columns

label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

transformed_file_path = "C:/Users/Jashwanth/OneDrive/Documents/MEDPREDICT/Cleaned Datasets/transformed_Thyroid_Diff.csv"  
df.to_csv(transformed_file_path, index=False)

print("Transformation complete. File saved at:", transformed_file_path)

Transformation complete. File saved at: C:/Users/Jashwanth/OneDrive/Documents/MEDPREDICT/Cleaned Datasets/transformed_Thyroid_Diff.csv